### ISSUE TITLE
不支持继承

### ISSUE THREAD

**Issue by donggelaile** [changsanjiang/SJDBMap#3]
父类的属性无法添加到数据库，我大概改了下源码支持了，但是不知是否会带来隐含的坑，还请作者指教下。
static NSMutableArray<NSString*>* _sj_get_tab_ivar_list_contain_inherit(Class<SJDBMapUseProtocol> cls)
{
    NSString *clsStr = NSStringFromClass(cls);
    NSMutableArray *finalIvarResult = @[].mutableCopy;
    
    while (![clsStr isEqualToString:@"NSObject"] && clsStr) {
        NSArray<NSString *> *ignoredIvarList = nil;
        if ( [(Class)cls respondsToSelector:@selector(tab_ignoredIvarList)] ) {
            ignoredIvarList = [(Class)cls tab_ignoredIvarList];
        }
        
        NSMutableArray *ivarListArrM = [NSMutableArray array];
        unsigned int outCount = 0;
        Ivar *ivarList = class_copyIvarList(cls, &outCount);
        if ( !ivarList ) return nil;
        if ( 0 == outCount ) return nil;
        for ( int i = 0 ; i < outCount ; ++i ) {
            const char *name = ivar_getName(ivarList[i]);
            NSString *nameStr = [NSString stringWithUTF8String:name];
            if ( [ignoredIvarList containsObject:nameStr] )
                continue;
            [ivarListArrM addObject:nameStr];
        }
        free(ivarList);
        [finalIvarResult addObjectsFromArray:ivarListArrM];
        
        cls = class_getSuperclass(cls);
        clsStr = NSStringFromClass(cls);
    }
    return finalIvarResult;
}

static NSArray<NSString *> *sj_get_tab_ivar_list(Class<SJDBMapUseProtocol> cls) {
    NSString *clsStr = NSStringFromClass(cls);
    static NSMutableDictionary<NSString *, NSArray<NSString *> *> *data;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        data = [NSMutableDictionary new];
    });
    
    if ( !data[clsStr] ) {
        data[clsStr] = _sj_get_tab_ivar_list_contain_inherit(cls).copy;
    }
    
    return data[clsStr];
}

**Comment by changsanjiang** [comment]
代码已重构, 新的库也支持继承了.
